# Generated by Django 3.1.4 on 2020-12-16 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0002_customer_meteringpoint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meteringpoint',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meteringpoint', to='masterdata.customer'),
        ),
    ]
